name: Create Azure Resources

on: 
  workflow_dispatch:    
  push:
    branches:
      - "main"
    paths:
      - "bicep/**/**.bicep"
      - ".github/workflows/infra.yml"

jobs:
  create-azure-resources:

    env: 
      LOCATION: 'canadacentral'
      DEPLOYMENT_NAME: aro-deployment

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Validate that bicep builds and build
        run: |
          bicep build ./bicep/main.bicep  
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
          
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.0
        with:        
          tokenPrefix: __        
          tokenSuffix: __        
          files: '["./bicep/main.parameters.json"]'
        env:          
          aadClientId: ${{ secrets.SP_AAD_CLIENT_ID }}
          aadClientSecret: ${{ secrets.SP_AAD_CLIENT_SECRET }}
          domain: ${{ secrets.DOMAIN }}


      - name: Deploy Azure Resource Manager (ARM) Template
        id: deployAzRes
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          scope: subscription
          deploymentName:  ${{ env.DEPLOYMENT_NAME }}
          region: ${{ env.LOCATION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./bicep/main.json
          parameters: ./bicep/main.parameters.json

